pages = [{"l":"index.html#","e":false,"i":"","n":"life","t":"life","d":"","k":"static"},
{"l":"app.html#","e":false,"i":"","n":"app","t":"app","d":"","k":"package"},
{"l":"app/Life$.html#","e":false,"i":"","n":"Life","t":"Life","d":"app","k":"object"},
{"l":"app/Life$.html#board-0","e":false,"i":"","n":"board","t":"board: Bounds","d":"app.Life","k":"val"},
{"l":"app/Life$.html#config-0","e":false,"i":"","n":"config","t":"config: Config","d":"app.Life","k":"val"},
{"l":"app/Life$.html#main-913","e":false,"i":"","n":"main","t":"main(args: Array[String]): Unit","d":"app.Life","k":"def"},
{"l":"app/Life$.html#viewport-0","e":false,"i":"","n":"viewport","t":"viewport: Bounds","d":"app.Life","k":"val"},
{"l":"app/Life$$Ansi$.html#","e":false,"i":"","n":"Ansi","t":"Ansi","d":"app.Life","k":"object"},
{"l":"app/Life$$Ansi$.html#clearScreen-0","e":false,"i":"","n":"clearScreen","t":"clearScreen: String","d":"app.Life.Ansi","k":"val"},
{"l":"app/Life$$Ansi$.html#home-0","e":false,"i":"","n":"home","t":"home: String","d":"app.Life.Ansi","k":"val"},
{"l":"life.html#","e":false,"i":"","n":"life","t":"life","d":"","k":"package"},
{"l":"life.html#+-9cd","e":false,"i":"Cell","n":"+","t":"+(offset: Position): Cell","d":"life","k":"def"},
{"l":"life.html#Cells-0","e":false,"i":"","n":"Cells","t":"Cells = Set[Cell]","d":"life","k":"type"},
{"l":"life.html#bounds-fffff319","e":false,"i":"Cells","n":"bounds","t":"bounds: Bounds","d":"life","k":"def"},
{"l":"life.html#neighbours-9e","e":false,"i":"Cell","n":"neighbours","t":"neighbours: List[Cell]","d":"life","k":"def"},
{"l":"life.html#nextGeneration-400","e":false,"i":"World","n":"nextGeneration","t":"nextGeneration: World","d":"life","k":"def"},
{"l":"life.html#prettified-fffff065","e":false,"i":"World","n":"prettified","t":"prettified: String","d":"life","k":"def"},
{"l":"life.html#rotate-927","e":false,"i":"Cells","n":"rotate","t":"rotate(n: Int): Set[Cell]","d":"life","k":"def"},
{"l":"life.html#unbounded-400","e":false,"i":"World","n":"unbounded","t":"unbounded: World","d":"life","k":"def"},
{"l":"life.html#withBounds-947","e":false,"i":"World","n":"withBounds","t":"withBounds(bounds: Bounds): World","d":"life","k":"def"},
{"l":"life.html#withCells-4d","e":false,"i":"World","n":"withCells","t":"withCells(cells: Cells, offset: Position): World","d":"life","k":"def"},
{"l":"life.html#withViewport-947","e":false,"i":"World","n":"withViewport","t":"withViewport(viewport: Bounds): World","d":"life","k":"def"},
{"l":"life.html#withoutViewport-400","e":false,"i":"World","n":"withoutViewport","t":"withoutViewport: World","d":"life","k":"def"},
{"l":"life/Bounds.html#","e":false,"i":"","n":"Bounds","t":"Bounds(rows: Range, columns: Range)","d":"life","k":"class"},
{"l":"life/Bounds$.html#","e":false,"i":"","n":"Bounds","t":"Bounds","d":"life","k":"object"},
{"l":"life/Bounds$.html#from-fffffed3","e":false,"i":"","n":"from","t":"from(config: Config): Bounds","d":"life.Bounds","k":"def"},
{"l":"life/Cell.html#","e":false,"i":"","n":"Cell","t":"Cell(row: Int, column: Int)","d":"life","k":"class"},
{"l":"life/Cells$.html#","e":false,"i":"","n":"Cells","t":"Cells","d":"life","k":"object"},
{"l":"life/Cells$.html#Error-0","e":false,"i":"","n":"Error","t":"Error = String","d":"life.Cells","k":"type"},
{"l":"life/Cells$.html#Result-0","e":false,"i":"","n":"Result","t":"Result = Either[Error, Cells]","d":"life.Cells","k":"type"},
{"l":"life/Cells$.html#fromFilename-fffffbe4","e":false,"i":"","n":"fromFilename","t":"fromFilename(filename: String): Result","d":"life.Cells","k":"def"},
{"l":"life/Cells$.html#fromText-fffffbe4","e":false,"i":"","n":"fromText","t":"fromText(s: String): Result","d":"life.Cells","k":"def"},
{"l":"life/Patterns$.html#","e":false,"i":"","n":"Patterns","t":"Patterns","d":"life","k":"object"},
{"l":"life/Patterns$.html#beacon-0","e":false,"i":"","n":"beacon","t":"beacon: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#beehive-0","e":false,"i":"","n":"beehive","t":"beehive: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#blinker-0","e":false,"i":"","n":"blinker","t":"blinker: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#block-0","e":false,"i":"","n":"block","t":"block: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#boat-0","e":false,"i":"","n":"boat","t":"boat: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#glider-0","e":false,"i":"","n":"glider","t":"glider: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#gliderGunGosper-0","e":false,"i":"","n":"gliderGunGosper","t":"gliderGunGosper: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#loaf-0","e":false,"i":"","n":"loaf","t":"loaf: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#pentaDecathlon-0","e":false,"i":"","n":"pentaDecathlon","t":"pentaDecathlon: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#pulsar-0","e":false,"i":"","n":"pulsar","t":"pulsar: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#random-fffff9f5","e":false,"i":"","n":"random","t":"random(board: Bounds): Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#spaceshipLightweight-0","e":false,"i":"","n":"spaceshipLightweight","t":"spaceshipLightweight: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#toad-0","e":false,"i":"","n":"toad","t":"toad: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Patterns$.html#tub-0","e":false,"i":"","n":"tub","t":"tub: Cells","d":"life.Patterns","k":"def"},
{"l":"life/Position.html#","e":false,"i":"","n":"Position","t":"Position(row: Int, column: Int)","d":"life","k":"class"},
{"l":"life/World.html#","e":false,"i":"","n":"World","t":"World(liveCells: Cells, maybeBounds: Option[Bounds], maybeViewport: Option[Bounds])","d":"life","k":"class"},
{"l":"life/World$.html#","e":false,"i":"","n":"World","t":"World","d":"life","k":"object"},
{"l":"life/World$.html#withCells-fffff2ae","e":false,"i":"","n":"withCells","t":"withCells(cells: Cells): World","d":"life.World","k":"def"}];